### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by LJGz** [benfulcher/hctsaDocumentation#1]
https://github.com/benfulcher/hctsaDocumentation/blob/master/overview_mysql_database.md links to https://github.com/benfulcher/hctsaDocumentation/blob/master/mysql_database.md which is 404.

## Installing the *hctsa* code package to work with a *mySQL* database

The *hctsa* package requires some preliminary set up to work with a *mySQL* database, described [here](mysql_database.md):

**Comment by benfulcher** [comment]
Thank you: should be fixed now!
FYI, if you're not already using the gitbooks interface, it's much nicer: https://hctsa-users.gitbook.io/hctsa-manual/
